### ISSUE TITLE
Copyright Problems

### ISSUE THREAD

**Issue by AfterRebelion** [The-Fireplace-Minecraft-Mods/TickDynamic#10]
Most of the code in /src/main/java/net/minecraft is MCP generated code from Mojang code, so it has Mojang copyright, and cannot be redistributed.

Aside from that, copyng entire classes (Entity and TileEntity, on top of that, as they are really huge) can lead to compatibility issues between mods, or even Forge versions.

**Comment by The-Fireplace** [comment]
Thanks for the heads up, I'll work on it. @wildex999 , how should I handle this?

**Comment by AfterRebelion** [comment]
From the look of it, the only thing that they do is make Entity and TileEntity extend your EntityObject.
And in theory, that change is already [done here](https://github.com/The-Fireplace/TickDynamic/blob/1.11.2_0.5_fix/src/main/java/com/wildex999/patcher/EntityInjector.java) with ASM, so it seems redundant.

**Comment by wildex999** [comment]
I'm quite sure that Everything in net/minecraft is not part of the compiled result, and wasn't realy planned to be part of the git commit(Except maybe temporary, before I dediced to open source the project).

The byte code injector will add stuff to the Entity and TileEntity classes, which I also try to access in the code. However, at compile time, the Entity and TileEntity class does not have the injected methods, so it will not compile.
As a hotfix I just added classes at compile time, but remove then from the resulting jar.

You should be able to just strip the whole class except the methods names and parameters, and it will still work. A better solution would of course find a way to just allow it to compile without needing to know about the added methods.

**Comment by The-Fireplace** [comment]
Interesting. Thanks, wildex. I haven't messed with much asm before this, so I wasn't sure, and I haven't had time to look too closely.
And come to think of it, those files aren't included in the mod jar, so I can go ahead and mark this issue as resolved, and make a mental note to myself to look in to removing those files from the project entirely.

**Comment by AfterRebelion** [comment]
You could for now add the directory to gitignore, so they aren't added to the project.

**Comment by The-Fireplace** [comment]
@AfterRebelion The problem with that is that my buildserver can only see files that are in the repo.
