### ISSUE TITLE
Tick Dynamic tries to work on other mods' non-tickable tile entities

### ISSUE THREAD

**Issue by hextrace** [The-Fireplace-Minecraft-Mods/TickDynamic#12]
[System Details](https://paste.ee/p/0i3NH)

**Issue:**  Console log spam with variations of: `Failed to remove: com.pengu.lostthaumaturgy.tile.TileCrystalOre@3e9399 as it does not exist in list: com.wildex999.tickdynamic.listinject.ListManager@4bb4ba87`

I was curious if there was a way to resolve this issue via your config files.  I'd rather not hack blindly; however, I've attempted to create a [new entry](https://paste.ee/p/0s6vu) for the offending tile entity by setting the `maxSlices` option to 0.  I'm considering setting the `minimumObjects` to 0 as it seems that the tileEntity is gone before Tick Dynamic is getting to it?

**Comment by The-Fireplace** [comment]
It does this to all modded tile entities, for now. I am working to find and resolve the issue. For now, to stop the log spam, there is a config option that lets you disable Tick Dynamic logging.

**Comment by hextrace** [comment]
Understood.  Thank you.
