### ISSUE TITLE
Advanced Rocketry Problems [adds 156 worlds] 

### ISSUE THREAD

**Issue by James-Webb554** [The-Fireplace-Minecraft-Mods/TickDynamic#13]
Hello, I wondered if you could help me with this issue. Advanced Rocketry adds something short of 150 different worlds. Of course with slices this gets a little crazy, Is there any way to whitelist or filter worlds you don't want slices to be applied to? Since some of these worlds if not (95%) of them will never be used.

**Comment by The-Fireplace** [comment]
If you don't want slices applied to them, that means they get as much time as they want, according to the [documentation](https://minecraft.curseforge.com/projects/tick-dynamic#title-3). If you want the unused ones to have less time allocated to them, I would set defaultWorldSlicesMax to a much lower value, so they get less, then raise the slices for dimensions you want to use to something higher.

I hope that helped, let me know if you have any more questions.
