### ISSUE TITLE
Server Crash on Client Join (1.12)

### ISSUE THREAD

**Issue by zacklmoore** [The-Fireplace-Minecraft-Mods/TickDynamic#14]
Hey just a crash to report. I have a whole bunch of mods installed so it might be something from another one of them but from logs it looked like it was from tickdynamic. Let me know if there is anything else I can provide to help with debugging!

Forge: 14.21.1.2413

Crash Report: 
https://pastebin.com/ZKFDRZyD

**Comment by The-Fireplace** [comment]
Does this happen every time a client joins? And have you tried with just TickDynamic present to see if the issue still occurs?

**Comment by The-Fireplace** [comment]
Closing due to no response
