### ISSUE TITLE
Incorrect warning saying "Copy is not valid"

### ISSUE THREAD

**Issue by Aphyxia** [The-Fireplace-Minecraft-Mods/TickDynamic#21]
I get the warning that my tickDynamic file is not valid: https://gyazo.com/b54487889e2bee3f17e2ed7189f51239

But it should be valid, considering what I've done:

Steps I took:
PC 1:
1) Downloaded from here https://minecraft.curseforge.com/projects/tick-dynamic  TickDynamic-1.12.2-1.0.0
2) Packed it in a .rar archive.
3) Uploaded to google drive

PC 2:

4) Downloaded the file.
5) Unzipped to mods folder
6) Ran game
7) Created new single player world

And on world start I got the warning in chat.

I don't know how you're checking if it's valid but something seems wrong.

forge 2619
mc 1.12.2
TickDynamic-1.12.2-1.0.0

**Comment by The-Fireplace** [comment]
Ignore that warning for this version. It isn't signed because my buildserver is down and I am waiting on it to come back up.

**Comment by auddie2015** [comment]
I was just coming to report this. I followed the link in the warning to make sure I had it right even though I downloaded it via Twitch which is the same repository. I shall ignore it for now. :-)

**Comment by MechanosG** [comment]
Same problem here with 1.12.2-1.0.0.  Just reporting it.  Will ignore the error.

**Comment by The-Fireplace** [comment]
Fixed in 1.0.1.
