### ISSUE TITLE
Sporadic Hard-Crashes Against Forge 2766

### ISSUE THREAD

**Issue by SalmonSays** [The-Fireplace-Minecraft-Mods/TickDynamic#29]
This was produced using "TickDynamic-1.12.2-1.0.1.jar" (installed on server-only) against "forge-1.12.2-14.23.5.2766-universal". This crash is somewhat sporadic, but I appear to get it no less than once within every 24 hour period and sometimes more frequently.

I loosely gather that it has something to do with removing from an ArrayList while iterating without using the Iterator Add/Remove methods; I'm still trying to track down the exact possible causes, though I suspect it *may* have something to do with server tick time being drawn out beyond the norm during bogged down world generation. As yet I haven't been able to catch it in the act to prove it for certain, so take that with a grain of salt because I could be off-base.

The server crash log is here:
https://hastebin.com/kokodivuku.rb

And the fml-server.log is here:
https://www.dropbox.com/s/u9t16r4oi560rq0/2018-10-15-5.log?dl=0

(On Dropbox because it's not sanitized for chat/usernames/etc; I'll pull the file at a future date when it's no longer of use)

**Comment by The-Fireplace** [comment]
Crash report is missing, try again when I upload 1.0.2
