### ISSUE TITLE
The Midnight mod Incompatibility

### ISSUE THREAD

**Issue by TheSexyYeti** [The-Fireplace-Minecraft-Mods/TickDynamic#37]
The makers of the mod The Midnight asked me to open an issue to inform you that your mod is incompatible with theirs. Cause the game to crash when you go through the portal for The Midnight dimension with an error report saying "The game crashed whilst exception ticking world entities. Error: java.util.ConcurrentModificationException: List modified before going to next entry.".

**Comment by The-Fireplace** [comment]
Try 1.0.2 when it comes out. Also, post a crash report next time, not just the first line of the exception.
