### ISSUE TITLE
Tick Dynamic not valid

### ISSUE THREAD

**Issue by Chancho91** [The-Fireplace-Minecraft-Mods/TickDynamic#49]
Here is my latest log. Link: https://pastebin.com/PwX10ZLt

**Comment by ghost** [comment]
I have the same issue on 1.0.2.

**Comment by GoobertFroobert** [comment]
I have the same issue for any version of Forge later than 1.12.2 (2811)

**Comment by Water-Moon** [comment]
It's some problem with the code... (Issue #44 is about the same thing...

**Comment by Macleykun** [comment]
I asked The_fireplace on forge if he can look into this. He'll do it when he get's the chance.

**Comment by The-Fireplace** [comment]
Fixed in 1.0.3
