### ISSUE TITLE
Crash with minecraft 1.11.2

### ISSUE THREAD

**Issue by KristjanKr** [The-Fireplace-Minecraft-Mods/TickDynamic#5]
Game crashes when trying to create new world:

Crashlog: https://paste.ee/p/pqUnJ
Forge: build 1.11.2 - 13.20.0.2315
Minecraft: 1.11.2
TickDynamic: 
TickDynamic-1.11.2-0.5.2

If you need anything else, then please let know.

**Comment by The-Fireplace** [comment]
Fixed in 0.5.3
