### ISSUE TITLE
"Invalid Copy of Tick Dynamic"

### ISSUE THREAD

**Issue by QazCetelic** [The-Fireplace-Minecraft-Mods/TickDynamic#54]
It says that the copy is invalid, what should I do.

I downloaded the file using GDLauncher, which should get it from CurseForge.

**Comment by Biviho** [comment]
i'm having the same problem downloading manually version 1.0.2 from curseforge. no problem with 1.0.1

**Comment by Water-Moon** [comment]
#44

**Comment by Macleykun** [comment]
I asked The_fireplace on forge if he can look into this. He'll do it when he get's the chance.

**Comment by The-Fireplace** [comment]
Fixed in 1.0.3
