### ISSUE TITLE
Botania and misc thrown item rubberbanding 1.11.2-0.5.3

### ISSUE THREAD

**Issue by Crumbology** [The-Fireplace-Minecraft-Mods/TickDynamic#7]
Thrown items rubberband quite horribly, enderpearls, tinkers shurikens and botania chakrams to name a few.

Quite a lot of Botania problems, chakrams I already mentioned, but luminizers also rubberband, sparks performance takes a big hit, gaia spawning additional mobs can take 5-10x as long as normal and his movement seems quite gimped too.

Frankly, Botania is reaching almost unusable levels of performance.

All the above problems disappeared when tick dynamic was removed from the server for testing, 1.11.2-0.5.2 had none of these issues.

Using Beyond Reality:Farscapes modpack from the AT launcher.[https://github.com/Beyond-Reality/Beyond-Realty-Farscapes/blob/master/modlist.md](url)

**Comment by The-Fireplace** [comment]
That's because TickDynamic basically offsets the lag from everything on to entities and tile entities. So instead of everything being slow, entities and tile entities tick slower, and everything else is faster.
0.5.2 and before were broken, and didn't work. Loading them pretty much did nothing.

**Comment by Crumbology** [comment]
Ah ok, so it's basically a choice for the server ops to make, seems a shame it makes so many items unusable but it is what it is, thanks.

**Comment by The-Fireplace** [comment]
No problem. Sorry you're having issues, if I knew of a better way to keep the TPS up, I would do it.
